SUPERVISOR_MODEL="gpt-4o"
SUPERVISOR_TEMPERATURE=0

GENERATOR_MODEL="gpt-4o"
GENERATOR_TEMPERATURE=0

ANALYST_MODEL="gpt-4o"
ANALYST_TEMPERATURE=0

VALIDATOR_MODEL="gpt-4o-mini"#"o3"
VALIDATOR_TEMPERATURE=0

EXTRACTOR_MODEL="gpt-4o-mini"
EXTRACTOR_TEMPERATURE=0

HUMAN_REVIEW_MODEL="gpt-4o-mini"
HUMAN_REVIEW_TEMPERATURE=0

CHAT_MODEL="gpt-4o-mini"
CHAT_TEMPERATURE=0